### ISSUE TITLE
run webui demo bug

### ISSUE THREAD

**Issue by PancakeAwesome** [openmedlab/XrayPULSE#4]
When running webui of run_demo.py, after running successfully, the web interface appears to upload medical images, and the error will occur

**Comment by zongzi3zz** [comment]
I can't view the screenshot, but I suggest that you can check your network.

**Comment by PancakeAwesome** [comment]
> I can't view the screenshot, but I suggest that you can check your network.

i run webui successful, but when i upload my local image file, will occur some errors on interface.

**Comment by zongzi3zz** [comment]
Can you show me some screenshots?
